/* PRISMON Boutique — Main Application Engine */
const PRODUCTS=[
{id:1,name:'Aura Radiance Serum',description:'A luminous vitamin C serum with hyaluronic acid and rosehip extract. Brightens, hydrates, and protects with a featherlight, fast-absorbing formula for all-day glow.',price:89,category:'skincare',stock:18,image:'https://images.unsplash.com/photo-1620916566398-39f1143ab7be?w=600&h=600&fit=crop&auto=format&q=80'},
{id:2,name:'Zenith Botanical Mist',description:'A refreshing rosewater and aloe vera facial mist infused with green tea antioxidants. Calms, tones, and sets makeup with a micro-fine, invisible veil.',price:45,category:'self-care',stock:30,image:'https://images.unsplash.com/photo-1556228578-0d85b1a4d571?w=600&h=600&fit=crop&auto=format&q=80'},
{id:3,name:'Onyx Detox Soap',description:'Handcrafted activated charcoal cleansing bar with tea tree oil and bentonite clay. Draws out impurities while maintaining the skin moisture barrier.',price:28,category:'self-care',stock:40,image:'https://images.unsplash.com/photo-1607006344380-b6775a0824a7?w=600&h=600&fit=crop&auto=format&q=80'},
{id:4,name:'Luna Glow Moisturizer',description:'Overnight repair cream with retinol, squalane, and ceramides. Deeply nourishes while you sleep, revealing plumper, firmer skin by morning.',price:65,category:'skincare',stock:15,image:'https://images.unsplash.com/photo-1611930022073-b7a4ba5fcccd?w=600&h=600&fit=crop&auto=format&q=80'},
{id:5,name:'Rose Quartz Face Roller',description:'Genuine rose quartz dual-ended roller for lymphatic drainage and product absorption. Cool stone surface de-puffs and sculpts facial contours naturally.',price:38,category:'tools',stock:25,image:'https://images.unsplash.com/photo-1590439471364-192aa70c0b53?w=600&h=600&fit=crop&auto=format&q=80'},
{id:6,name:'Velvet Night Cream',description:'Rich peptide-infused night cream with bakuchiol and jojoba. Targets fine lines and uneven texture while deeply hydrating through the night.',price:78,category:'skincare',stock:10,image:'https://images.unsplash.com/photo-1620916566398-39f1143ab7be?q=80&w=600&auto=format&fit=crop'},
{id:7,name:'Crystal Clear Toner',description:'Gentle exfoliating toner with PHA, niacinamide, and centella asiatica. Refines pores and evens skin tone without stripping or irritating sensitive skin.',price:42,category:'skincare',stock:22,image:'https://images.unsplash.com/photo-1556228720-195a672e8a03?w=600&h=600&fit=crop&auto=format&q=80'},
{id:8,name:'Jade Harmony Mask',description:'Kaolin clay purifying mask with matcha, spirulina, and French green clay. A 10-minute ritual that detoxifies pores and leaves skin velvety soft.',price:55,category:'self-care',stock:12,image:'https://images.unsplash.com/photo-1596755389378-c31d21fd1273?w=600&h=600&fit=crop&auto=format&q=80'},
{id:9,name:'Silk Gua Sha Stone',description:'Hand-carved nephrite jade gua sha for tension release and facial sculpting. Promotes circulation and reduces puffiness with traditional techniques.',price:32,category:'tools',stock:28,image:'https://images.unsplash.com/photo-1608248543803-ba4f8c70ae0b?w=600&h=600&fit=crop&auto=format&q=80'},
{id:10,name:'Golden Hour Body Oil',description:'Dry-touch body oil with argan, marula, and vitamin E. Absorbs instantly leaving a satin-smooth luminous finish without greasy residue.',price:58,category:'self-care',stock:20,image:'https://images.unsplash.com/photo-1573461160327-b450ce3d8e7f?w=600&h=600&fit=crop&auto=format&q=80'}
];
let currentFilter='all',currentSort='default',checkoutStep=1,checkoutData={shipping:{},payment:{}};
function catLabel(c){return c.split('-').map(w=>w[0].toUpperCase()+w.slice(1)).join(' ')}
const Cart={
KEY:'prismon_cart',
get(){try{return JSON.parse(localStorage.getItem(this.KEY))||[]}catch{return[]}},
save(c){localStorage.setItem(this.KEY,JSON.stringify(c));this.badge()},
add(id){const p=PRODUCTS.find(x=>x.id===id);if(!p)return;if(p.stock<=0){Toast.show('Out of stock','error');return}const c=this.get(),e=c.find(i=>i.id===id);if(e){if(e.qty>=p.stock){Toast.show('Maximum stock reached','warning');return}e.qty++}else c.push({id,qty:1});this.save(c);Toast.show(p.name+' added to cart','success');renderCartContent()},
remove(id){this.save(this.get().filter(i=>i.id!==id));renderCartContent()},
updateQty(id,d){const c=this.get(),i=c.find(x=>x.id===id),p=PRODUCTS.find(x=>x.id===id);if(!i||!p)return;i.qty+=d;if(i.qty<=0){this.remove(id);return}if(i.qty>p.stock){Toast.show('Maximum stock reached','warning');i.qty=p.stock}this.save(c);renderCartContent()},
total(){return this.get().reduce((s,i)=>{const p=PRODUCTS.find(x=>x.id===i.id);return s+(p?p.price*i.qty:0)},0)},
count(){return this.get().reduce((s,i)=>s+i.qty,0)},
clear(){localStorage.removeItem(this.KEY);this.badge()},
badge(){const b=document.getElementById('cart-badge'),n=this.count();if(!b)return;b.textContent=n;if(n>0){b.classList.remove('hidden');b.classList.add('flex')}else{b.classList.add('hidden');b.classList.remove('flex')}}
};
const Toast={show(msg,type='info'){const c=document.getElementById('toast-container');if(!c)return;const colors={success:'border-l-emerald-500 bg-emerald-50',error:'border-l-red-500 bg-red-50',warning:'border-l-amber-500 bg-amber-50',info:'border-l-accent bg-accent-pale'};const icons={success:'✓',error:'✕',warning:'⚠',info:'ℹ'};const t=document.createElement('div');t.className=`toast-enter flex items-center gap-3 px-5 py-3.5 rounded-xl border-l-4 ${colors[type]||colors.info} text-gray-800 text-sm font-medium shadow-lg border border-gray-100 min-w-[280px]`;t.innerHTML=`<span class="w-5 h-5 rounded-full flex items-center justify-center text-xs font-bold ${type==='error'?'bg-red-100 text-red-600':type==='warning'?'bg-amber-100 text-amber-600':type==='success'?'bg-emerald-100 text-emerald-600':'bg-accent-pale text-accent'}">${icons[type]||icons.info}</span><span>${msg}</span>`;c.appendChild(t);setTimeout(()=>{t.classList.remove('toast-enter');t.classList.add('toast-exit');t.addEventListener('animationend',()=>t.remove())},3000)}};
function navigate(hash){window.location.hash=hash}
function handleRoute(){
const hash=window.location.hash.slice(1)||'home';const app=document.getElementById('app');
if(!app)return;
const isColl=hash==='catalog'||hash.startsWith('category/');
document.querySelectorAll('.nav-link').forEach(l=>{const n=l.dataset.nav;if(n==='catalog'){l.classList.toggle('text-accent',isColl);l.classList.toggle('text-gray-400',!isColl)}else{l.classList.toggle('text-accent',n===hash);l.classList.toggle('text-gray-400',n!==hash)}});
if(hash==='home')renderHome(app);else if(hash==='catalog')renderCatalog(app);else if(hash==='checkout')renderCheckout(app);else if(hash.startsWith('category/')){renderCategoryPage(app,hash.substring(9))}else renderHome(app);
window.scrollTo({top:0,behavior:'smooth'});
}
function footerHTML(){return `<footer class="bg-gray-50 border-t border-gray-100 mt-20"><div class="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8 py-16"><div class="grid grid-cols-2 md:grid-cols-4 gap-8 lg:gap-12">
<div><h4 class="font-serif font-bold text-gray-900 mb-4">About Us</h4><p class="text-gray-400 text-sm leading-relaxed">Prismon Black is a curated boutique for premium self-care and skincare. We believe in the ritual of beauty.</p><a href="about.html" class="text-accent text-sm mt-3 inline-block hover:underline transition-colors">Learn More →</a></div>
<div><h4 class="font-serif font-bold text-gray-900 mb-4">Customer Care</h4><ul class="space-y-2.5"><li><a href="shipping.html" class="text-gray-400 text-sm hover:text-accent transition-colors">Shipping &amp; Returns</a></li><li><a href="contact.html" class="text-gray-400 text-sm hover:text-accent transition-colors">Contact Us</a></li><li><a href="faqs.html" class="text-gray-400 text-sm hover:text-accent transition-colors">FAQs</a></li></ul></div>
<div><h4 class="font-serif font-bold text-gray-900 mb-4">Follow Us</h4><ul class="space-y-2.5"><li class="flex items-center gap-2.5"><svg class="w-4 h-4 text-gray-400" fill="none" stroke="currentColor" stroke-width="1.5" viewBox="0 0 24 24"><rect x="2" y="2" width="20" height="20" rx="5"/><path d="M16 11.37A4 4 0 1112.63 8 4 4 0 0116 11.37z"/><line x1="17.5" y1="6.5" x2="17.51" y2="6.5"/></svg><a href="https://www.instagram.com/erro_rcodee" target="_blank" class="text-gray-400 text-sm hover:text-accent transition-colors">Instagram</a></li><li class="flex items-center gap-2.5"><svg class="w-4 h-4 text-gray-400" fill="currentColor" viewBox="0 0 24 24"><path d="M23.498 6.186a3.016 3.016 0 00-2.122-2.136C19.505 3.545 12 3.545 12 3.545s-7.505 0-9.377.505A3.017 3.017 0 00.502 6.186C0 8.07 0 12 0 12s0 3.93.502 5.814a3.016 3.016 0 002.122 2.136c1.871.505 9.376.505 9.376.505s7.505 0 9.377-.505a3.015 3.015 0 002.122-2.136C24 15.93 24 12 24 12s0-3.93-.502-5.814zM9.545 15.568V8.432L15.818 12l-6.273 3.568z"/></svg><a href="https://www.youtube.com/@Bingxxo" target="_blank" class="text-gray-400 text-sm hover:text-accent transition-colors">YouTube</a></li><li class="flex items-center gap-2.5"><svg class="w-4 h-4 text-gray-400" fill="none" stroke="currentColor" stroke-width="1.5" viewBox="0 0 24 24"><circle cx="12" cy="12" r="10"/><path d="M2 12h20M12 2a15.3 15.3 0 014 10 15.3 15.3 0 01-4 10 15.3 15.3 0 01-4-10 15.3 15.3 0 014-10z"/></svg><a href="https://portfolio-rishav.pages.dev/" target="_blank" class="text-gray-400 text-sm hover:text-accent transition-colors">Portfolio</a></li></ul></div>
<div><h4 class="font-serif font-bold text-gray-900 mb-4">Legal</h4><ul class="space-y-2.5"><li><a href="privacy.html" class="text-gray-400 text-sm hover:text-accent transition-colors">Privacy Policy</a></li><li><a href="terms.html" class="text-gray-400 text-sm hover:text-accent transition-colors">Terms of Service</a></li></ul></div>
</div><div class="border-t border-gray-200 mt-12 pt-8 flex flex-col sm:flex-row items-center justify-between gap-4"><span class="font-serif text-sm font-bold text-gray-900 tracking-tight"><span class="font-extralight text-accent">P</span>R<span class="font-bold text-accent">I</span>SMON</span><p class="text-gray-400 text-xs tracking-wider">© 2026 Prismon Black. All rights reserved.</p></div></div></footer>`}
function categorySidebar(active){const cats=[...new Set(PRODUCTS.map(p=>p.category))];return `<aside class="hidden lg:block w-44 flex-shrink-0 pt-1"><h4 class="font-serif text-sm font-bold text-gray-900 mb-4 tracking-wide">Shop By</h4><ul class="space-y-2.5"><li><a href="#catalog" class="text-sm ${!active?'text-accent font-medium':'text-gray-400 hover:text-accent'} transition-colors">All Products</a></li>${cats.map(c=>`<li><a href="#category/${c}" class="text-sm ${active===c?'text-accent font-medium':'text-gray-400 hover:text-accent'} transition-colors">${catLabel(c)}</a></li>`).join('')}</ul></aside>`}
function mobileCatPills(active){const cats=[...new Set(PRODUCTS.map(p=>p.category))];return `<div class="flex flex-wrap gap-2 mb-6 lg:hidden"><a href="#catalog" class="filter-pill px-4 py-2 rounded-full text-xs font-medium uppercase tracking-wider border border-gray-200 ${!active?'active':''}">All</a>${cats.map(c=>`<a href="#category/${c}" class="filter-pill px-4 py-2 rounded-full text-xs font-medium uppercase tracking-wider border border-gray-200 ${active===c?'active':''}">${catLabel(c)}</a>`).join('')}</div>`}
function renderHome(app){const featured=PRODUCTS.slice(0,4);app.innerHTML=`
<section class="min-h-[calc(100vh-4rem)] flex items-center py-16 lg:py-0 overflow-hidden"><div class="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8 w-full"><div class="grid grid-cols-1 lg:grid-cols-2 gap-12 lg:gap-20 items-center">
<div class="space-y-7 fade-in-up"><p class="text-accent text-xs sm:text-sm font-semibold tracking-[.4em] uppercase">Clean Beauty, Elevated</p><h1 class="font-serif text-5xl sm:text-6xl lg:text-7xl font-bold text-gray-900 leading-[1.05]">The Art of<br><span class="text-accent italic">Self-Care</span></h1><p class="text-gray-400 text-base sm:text-lg max-w-md leading-relaxed">Botanical skincare rituals crafted from nature's finest ingredients. Discover your glow with formulations rooted in science and soul.</p><button onclick="navigate('catalog')" class="btn-primary px-10 py-4 bg-gray-900 text-white font-semibold text-sm uppercase tracking-[.2em] rounded-full shadow-md fiu-1">Explore the Collection</button></div>
<div class="relative fiu-2"><img src="https://images.unsplash.com/photo-1596462502278-27bfdc403348?w=800&h=1000&fit=crop&auto=format&q=80" alt="Premium skincare" class="w-full aspect-[4/5] object-cover rounded-3xl shadow-xl" onerror="this.style.display='none'"><div class="absolute -bottom-5 left-4 sm:-left-6 bg-white rounded-2xl shadow-lg p-5 border border-gray-100 z-10"><div class="flex items-center gap-3"><div class="w-10 h-10 rounded-full bg-accent-pale flex items-center justify-center text-accent font-bold text-sm">🌿</div><div><p class="font-serif text-lg font-bold text-gray-900">100% Natural</p><p class="text-gray-400 text-xs">Clean Ingredients</p></div></div></div></div>
</div></div></section>
<section class="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8 py-24"><div class="text-center mb-16"><p class="text-accent text-xs font-semibold tracking-[.3em] uppercase mb-3">Curated Selection</p><h2 class="font-serif text-3xl sm:text-4xl font-bold text-gray-900">Bestsellers</h2></div><div class="grid grid-cols-1 sm:grid-cols-2 lg:grid-cols-4 gap-6">${featured.map(p=>productCard(p)).join('')}</div><div class="text-center mt-12"><button onclick="navigate('catalog')" class="px-8 py-3 bg-white border border-gray-200 text-gray-700 rounded-full text-sm font-medium tracking-[.15em] uppercase hover:border-accent hover:text-accent transition-all duration-300">View All Products →</button></div></section>
<section class="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8 py-16"><div class="grid grid-cols-1 md:grid-cols-3 gap-6">
<div class="group flex items-center gap-4 p-6 rounded-2xl bg-gray-50 border border-gray-100 hover:-translate-y-1 hover:shadow-md transition-all duration-300 cursor-default"><div class="w-11 h-11 rounded-xl bg-accent-pale flex items-center justify-center text-lg flex-shrink-0">📦</div><div><h4 class="text-sm font-bold text-gray-900">Free Shipping</h4><p class="text-gray-400 text-xs mt-0.5">On every order, always</p></div></div>
<div class="group flex items-center gap-4 p-6 rounded-2xl bg-gray-50 border border-gray-100 hover:-translate-y-1 hover:shadow-md transition-all duration-300 cursor-default"><div class="w-11 h-11 rounded-xl bg-accent-pale flex items-center justify-center text-lg flex-shrink-0">🐰</div><div><h4 class="text-sm font-bold text-gray-900">Cruelty-Free</h4><p class="text-gray-400 text-xs mt-0.5">Never tested on animals</p></div></div>
<div class="group flex items-center gap-4 p-6 rounded-2xl bg-gray-50 border border-gray-100 hover:-translate-y-1 hover:shadow-md transition-all duration-300 cursor-default"><div class="w-11 h-11 rounded-xl bg-accent-pale flex items-center justify-center text-lg flex-shrink-0">🌿</div><div><h4 class="text-sm font-bold text-gray-900">Vegan Formula</h4><p class="text-gray-400 text-xs mt-0.5">100% plant-based goodness</p></div></div>
</div></section>
<section class="border-t border-gray-100 bg-gray-50/60"><div class="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8 py-24"><div class="text-center mb-14"><p class="text-accent text-xs font-semibold tracking-[.3em] uppercase mb-3">What Our Clients Say</p><h2 class="font-serif text-3xl sm:text-4xl font-bold text-gray-900">Testimonials</h2></div><div class="grid grid-cols-1 md:grid-cols-3 gap-6">
<div class="bg-white rounded-2xl p-8 shadow-sm border border-gray-100 hover:shadow-md transition-shadow"><div class="text-accent text-lg tracking-wider mb-4">★★★★★</div><p class="font-serif text-gray-700 italic leading-relaxed">"My skin has never felt so radiant. The Aura Serum is an absolute game-changer for my morning ritual."</p><div class="mt-6 pt-4 border-t border-gray-100"><p class="text-sm font-semibold text-gray-900">Sophia Laurent</p><p class="text-xs text-gray-400 mt-0.5">Verified Buyer</p></div></div>
<div class="bg-white rounded-2xl p-8 shadow-sm border border-gray-100 hover:shadow-md transition-shadow"><div class="text-accent text-lg tracking-wider mb-4">★★★★★</div><p class="font-serif text-gray-700 italic leading-relaxed">"The Velvet Night Cream transformed my nighttime routine. I wake up with visibly plumper, glowing skin every single morning."</p><div class="mt-6 pt-4 border-t border-gray-100"><p class="text-sm font-semibold text-gray-900">Amara Chen</p><p class="text-xs text-gray-400 mt-0.5">Verified Buyer</p></div></div>
<div class="bg-white rounded-2xl p-8 shadow-sm border border-gray-100 hover:shadow-md transition-shadow"><div class="text-accent text-lg tracking-wider mb-4">★★★★★</div><p class="font-serif text-gray-700 italic leading-relaxed">"Finally a brand that delivers on its promises. Clean ingredients, stunning packaging, and results I can actually see."</p><div class="mt-6 pt-4 border-t border-gray-100"><p class="text-sm font-semibold text-gray-900">Elena Rossi</p><p class="text-xs text-gray-400 mt-0.5">Verified Buyer</p></div></div>
</div></div></section>${footerHTML()}`}
function productCard(p){return `<div class="product-card bg-white rounded-3xl cursor-pointer group shadow-sm border border-gray-100 overflow-hidden" onclick="openModal(${p.id})"><div class="p-3"><div class="relative aspect-square overflow-hidden rounded-2xl bg-gray-50"><img src="${p.image}" alt="${p.name}" class="w-full h-full object-cover transition-transform duration-700 group-hover:scale-105" loading="lazy" onerror="this.style.display='none'"><div class="absolute inset-0 bg-black/0 group-hover:bg-black/5 transition-all duration-500 flex items-center justify-center rounded-2xl"><span class="text-gray-900 font-semibold tracking-[.15em] uppercase text-xs opacity-0 group-hover:opacity-100 transform translate-y-4 group-hover:translate-y-0 transition-all duration-500 px-5 py-2.5 rounded-full bg-white/90 shadow-md">Quick View</span></div>${p.stock<=3?`<span class="absolute top-3 right-3 px-2.5 py-1 bg-red-500 text-white text-[10px] font-bold tracking-wider uppercase rounded-full shadow-md">Low Stock</span>`:''}</div></div><div class="px-5 pb-5 pt-1"><span class="text-[10px] font-semibold uppercase tracking-[.25em] text-accent">${catLabel(p.category)}</span><h3 class="font-serif text-base font-semibold mt-1.5 text-gray-900 group-hover:text-accent transition-colors">${p.name}</h3><p class="text-xl font-bold mt-2.5 text-gray-900">$${p.price}</p></div></div>`}
function renderCatalog(app){app.innerHTML=`
<section class="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8 py-12 sm:py-16"><div class="text-center mb-12"><p class="text-accent text-xs font-semibold tracking-[.3em] uppercase mb-3">The Collection</p><h1 class="font-serif text-3xl sm:text-5xl font-bold text-gray-900">All Products</h1></div>
${mobileCatPills(null)}
<div class="flex gap-8">${categorySidebar(null)}<div class="flex-1">
<div class="flex justify-end mb-6"><select id="sort-select" class="bg-white border border-gray-200 rounded-full px-4 py-2.5 text-xs font-medium tracking-wider uppercase text-gray-600 appearance-none cursor-pointer hover:border-accent transition-colors pr-8" style="background-image:url('data:image/svg+xml,<svg xmlns=%22http://www.w3.org/2000/svg%22 width=%2212%22 height=%2212%22 viewBox=%220 0 24 24%22 fill=%22none%22 stroke=%22%236b7280%22 stroke-width=%222%22><polyline points=%226 9 12 15 18 9%22/></svg>');background-repeat:no-repeat;background-position:right 12px center"><option value="default" ${currentSort==='default'?'selected':''}>Sort By</option><option value="low" ${currentSort==='low'?'selected':''}>Price: Low → High</option><option value="high" ${currentSort==='high'?'selected':''}>Price: High → Low</option></select></div>
<div class="grid grid-cols-1 sm:grid-cols-2 xl:grid-cols-3 gap-6">${getFilteredProducts().map(p=>productCard(p)).join('')}</div>
${getFilteredProducts().length===0?'<p class="text-center text-gray-400 py-20 text-lg">No products found.</p>':''}
</div></div></section>${footerHTML()}`;
document.getElementById('sort-select').addEventListener('change',e=>{currentSort=e.target.value;renderCatalog(document.getElementById('app'))});
}
function renderCategoryPage(app,category){const products=getCategoryProducts(category);const title=catLabel(category);app.innerHTML=`
<section class="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8 py-12 sm:py-16"><div class="text-center mb-12"><p class="text-accent text-xs font-semibold tracking-[.3em] uppercase mb-3">Category</p><h1 class="font-serif text-3xl sm:text-5xl font-bold text-gray-900">Shop the ${title} Collection</h1></div>
${mobileCatPills(category)}
<div class="flex gap-8">${categorySidebar(category)}<div class="flex-1">
<div class="flex justify-end mb-6"><select id="sort-select" class="bg-white border border-gray-200 rounded-full px-4 py-2.5 text-xs font-medium tracking-wider uppercase text-gray-600 appearance-none cursor-pointer hover:border-accent transition-colors pr-8" style="background-image:url('data:image/svg+xml,<svg xmlns=%22http://www.w3.org/2000/svg%22 width=%2212%22 height=%2212%22 viewBox=%220 0 24 24%22 fill=%22none%22 stroke=%22%236b7280%22 stroke-width=%222%22><polyline points=%226 9 12 15 18 9%22/></svg>');background-repeat:no-repeat;background-position:right 12px center"><option value="default" ${currentSort==='default'?'selected':''}>Sort By</option><option value="low" ${currentSort==='low'?'selected':''}>Price: Low → High</option><option value="high" ${currentSort==='high'?'selected':''}>Price: High → Low</option></select></div>
<div class="grid grid-cols-1 sm:grid-cols-2 xl:grid-cols-3 gap-6">${products.map(p=>productCard(p)).join('')}</div>
${products.length===0?'<p class="text-center text-gray-400 py-20 text-lg">No products in this category.</p>':''}
</div></div></section>${footerHTML()}`;
document.getElementById('sort-select').addEventListener('change',e=>{currentSort=e.target.value;renderCategoryPage(document.getElementById('app'),category)});
}
function getFilteredProducts(){let list=[...PRODUCTS];if(currentSort==='low')list.sort((a,b)=>a.price-b.price);else if(currentSort==='high')list.sort((a,b)=>b.price-a.price);return list}
function getCategoryProducts(cat){let list=PRODUCTS.filter(p=>p.category===cat);if(currentSort==='low')list.sort((a,b)=>a.price-b.price);else if(currentSort==='high')list.sort((a,b)=>b.price-a.price);return list}
function openModal(id){const p=PRODUCTS.find(x=>x.id===id);if(!p)return;const modal=document.getElementById('product-modal');const content=document.getElementById('modal-content');if(!modal||!content)return;const inCart=Cart.get().find(i=>i.id===id);
content.innerHTML=`<div class="grid grid-cols-1 md:grid-cols-2 gap-0"><div class="aspect-square bg-gray-50 overflow-hidden rounded-t-3xl md:rounded-l-3xl md:rounded-tr-none p-6"><img src="${p.image}" alt="${p.name}" class="w-full h-full object-cover rounded-2xl" onerror="this.style.display='none'"></div><div class="p-8 flex flex-col justify-center"><span class="text-[10px] font-semibold uppercase tracking-[.3em] text-accent mb-2">${catLabel(p.category)}</span><h2 class="font-serif text-2xl sm:text-3xl font-bold text-gray-900">${p.name}</h2><p class="text-gray-400 text-sm leading-relaxed mt-4">${p.description}</p><div class="flex items-center gap-4 mt-6"><span class="text-3xl font-black text-gray-900">$${p.price}</span><span class="text-xs uppercase tracking-wider ${p.stock>5?'text-emerald-500':p.stock>0?'text-amber-500':'text-red-500'}">${p.stock>5?'In Stock':p.stock>0?'Only '+p.stock+' left':'Out of Stock'}</span></div><button onclick="Cart.add(${p.id});closeModal()" class="btn-primary mt-8 w-full py-4 bg-gray-900 text-white font-bold text-sm uppercase tracking-[.2em] rounded-full ${p.stock<=0?'opacity-30 pointer-events-none':''}">${p.stock<=0?'Sold Out':inCart?'Add Another':'Add to Cart'}</button><button onclick="closeModal()" class="mt-3 w-full py-3 text-gray-400 text-xs font-medium uppercase tracking-[.15em] hover:text-gray-600 transition-colors">Continue Browsing</button></div></div><button onclick="closeModal()" class="absolute top-4 right-4 w-10 h-10 rounded-full bg-gray-100 hover:bg-gray-200 flex items-center justify-center transition-colors text-gray-400 hover:text-gray-800" aria-label="Close"><svg class="w-5 h-5" fill="none" stroke="currentColor" stroke-width="2" viewBox="0 0 24 24"><line x1="18" y1="6" x2="6" y2="18"/><line x1="6" y1="6" x2="18" y2="18"/></svg></button>`;
modal.classList.remove('hidden');document.body.style.overflow='hidden'}
function closeModal(){const m=document.getElementById('product-modal');if(m)m.classList.add('hidden');document.body.style.overflow=''}
function toggleCart(){const drawer=document.getElementById('cart-drawer'),overlay=document.getElementById('cart-overlay'),chatW=document.getElementById('chat-widget');if(!drawer||!overlay)return;const isOpen=!drawer.classList.contains('translate-x-full');if(isOpen){drawer.classList.add('translate-x-full');overlay.classList.add('opacity-0','pointer-events-none');overlay.classList.remove('opacity-100','pointer-events-auto');document.body.style.overflow='';if(chatW)chatW.classList.remove('hidden')}else{renderCartContent();drawer.classList.remove('translate-x-full');overlay.classList.remove('opacity-0','pointer-events-none');overlay.classList.add('opacity-100','pointer-events-auto');document.body.style.overflow='hidden';if(chatW)chatW.classList.add('hidden')}}
function renderCartContent(){const c=Cart.get(),el=document.getElementById('cart-content');if(!el)return;
if(c.length===0){el.innerHTML=`<div class="flex items-center justify-between p-6 border-b border-gray-100"><h2 class="font-serif text-lg font-bold text-gray-900">Your Cart</h2><button onclick="toggleCart()" class="w-8 h-8 rounded-full hover:bg-gray-100 flex items-center justify-center transition-colors text-gray-400 hover:text-gray-800"><svg class="w-4 h-4" fill="none" stroke="currentColor" stroke-width="2" viewBox="0 0 24 24"><line x1="18" y1="6" x2="6" y2="18"/><line x1="6" y1="6" x2="18" y2="18"/></svg></button></div><div class="flex-1 flex flex-col items-center justify-center px-6 text-center"><div class="w-16 h-16 rounded-2xl bg-gray-50 flex items-center justify-center mb-4 text-2xl text-gray-300">🌿</div><p class="text-gray-400 text-sm">Your cart is empty</p><button onclick="toggleCart();navigate('catalog')" class="mt-6 px-6 py-2.5 bg-white border border-gray-200 rounded-full text-xs font-medium tracking-[.15em] uppercase text-gray-700 hover:border-accent hover:text-accent transition-colors">Browse Collection</button></div>`;return}
const total=Cart.total();el.innerHTML=`
<div class="flex items-center justify-between p-6 border-b border-gray-100"><h2 class="font-serif text-lg font-bold text-gray-900">Your Cart <span class="text-accent text-sm font-normal font-sans">(${Cart.count()})</span></h2><button onclick="toggleCart()" class="w-8 h-8 rounded-full hover:bg-gray-100 flex items-center justify-center transition-colors text-gray-400 hover:text-gray-800"><svg class="w-4 h-4" fill="none" stroke="currentColor" stroke-width="2" viewBox="0 0 24 24"><line x1="18" y1="6" x2="6" y2="18"/><line x1="6" y1="6" x2="18" y2="18"/></svg></button></div>
<div class="flex-1 overflow-y-auto p-6 space-y-4">${c.map(item=>{const p=PRODUCTS.find(x=>x.id===item.id);if(!p)return'';return `<div class="flex gap-4 p-4 rounded-2xl bg-gray-50/70 border border-gray-100 hover:border-gray-200 transition-colors"><div class="w-20 h-20 rounded-xl overflow-hidden bg-gray-100 flex-shrink-0"><img src="${p.image}" alt="${p.name}" class="w-full h-full object-cover" onerror="this.style.display='none'"></div><div class="flex-1 min-w-0"><h4 class="text-sm font-semibold text-gray-900 truncate">${p.name}</h4><p class="text-accent text-sm font-bold mt-1">$${p.price}</p><div class="flex items-center justify-between mt-2"><div class="flex items-center gap-2"><button onclick="Cart.updateQty(${p.id},-1)" class="qty-btn w-7 h-7 rounded-lg border border-gray-200 flex items-center justify-center text-xs text-gray-500">−</button><span class="text-sm font-medium w-6 text-center text-gray-800">${item.qty}</span><button onclick="Cart.updateQty(${p.id},1)" class="qty-btn w-7 h-7 rounded-lg border border-gray-200 flex items-center justify-center text-xs text-gray-500">+</button></div><button onclick="Cart.remove(${p.id})" class="text-gray-300 hover:text-red-500 transition-colors" title="Remove"><svg class="w-4 h-4" fill="none" stroke="currentColor" stroke-width="2" viewBox="0 0 24 24"><path stroke-linecap="round" stroke-linejoin="round" d="M19 7l-.867 12.142A2 2 0 0116.138 21H7.862a2 2 0 01-1.995-1.858L5 7m5 4v6m4-6v6m1-10V4a1 1 0 00-1-1h-4a1 1 0 00-1 1v3M4 7h16"/></svg></button></div></div></div>`}).join('')}</div>
<div class="p-6 border-t border-gray-100 space-y-4"><div class="flex justify-between text-sm"><span class="text-gray-400">Subtotal</span><span class="font-semibold text-gray-900">$${total.toFixed(2)}</span></div><div class="flex justify-between text-sm"><span class="text-gray-400">Shipping</span><span class="text-accent text-xs font-medium">FREE</span></div><div class="flex justify-between text-lg pt-2 border-t border-gray-100"><span class="font-bold text-gray-900">Total</span><span class="font-black text-gray-900">$${total.toFixed(2)}</span></div><button onclick="toggleCart();checkoutStep=1;navigate('checkout')" class="btn-primary w-full py-4 bg-gray-900 text-white font-bold text-sm uppercase tracking-[.2em] rounded-full">Checkout</button></div>`}
function renderCheckout(app){const cart=Cart.get();if(cart.length===0&&checkoutStep<4){navigate('catalog');Toast.show('Your cart is empty','info');return}
const steps=['Shipping','Payment','Review'];const progressHTML=`<div class="flex items-center justify-center gap-0 mb-12">${steps.map((s,i)=>`<div class="flex items-center"><div class="flex flex-col items-center"><div class="step-dot w-8 h-8 rounded-full flex items-center justify-center text-xs font-bold border-2 ${i+1<checkoutStep?'done border-accent text-white':''}${i+1===checkoutStep?'active border-accent text-white':''}${i+1>checkoutStep?'border-gray-200 text-gray-300':''}">${i+1<checkoutStep?'✓':i+1}</div><span class="text-[10px] mt-2 tracking-wider uppercase ${i+1<=checkoutStep?'text-accent':'text-gray-300'}">${s}</span></div>${i<steps.length-1?`<div class="step-line w-16 sm:w-24 h-0.5 mx-2 mb-5 ${i+1<checkoutStep?'done':'bg-gray-200'}"></div>`:''}</div>`).join('')}</div>`;
let formHTML='';
if(checkoutStep===1){formHTML=`<div class="bg-white rounded-2xl p-8 max-w-lg mx-auto scale-in shadow-lg border border-gray-100"><h2 class="font-serif text-xl font-bold text-gray-900 mb-6">Shipping Information</h2><div class="space-y-4" id="shipping-form"><div class="grid grid-cols-2 gap-4"><div><label class="text-[10px] uppercase tracking-[.2em] text-gray-400 block mb-1.5">First Name</label><input type="text" id="s-fname" class="w-full bg-gray-50 border border-gray-200 rounded-xl px-4 py-3 text-sm text-gray-800" placeholder="John" value="${checkoutData.shipping.fname||''}"></div><div><label class="text-[10px] uppercase tracking-[.2em] text-gray-400 block mb-1.5">Last Name</label><input type="text" id="s-lname" class="w-full bg-gray-50 border border-gray-200 rounded-xl px-4 py-3 text-sm text-gray-800" placeholder="Doe" value="${checkoutData.shipping.lname||''}"></div></div><div><label class="text-[10px] uppercase tracking-[.2em] text-gray-400 block mb-1.5">Email</label><input type="email" id="s-email" class="w-full bg-gray-50 border border-gray-200 rounded-xl px-4 py-3 text-sm text-gray-800" placeholder="john@example.com" value="${checkoutData.shipping.email||''}"></div><div><label class="text-[10px] uppercase tracking-[.2em] text-gray-400 block mb-1.5">Address</label><input type="text" id="s-address" class="w-full bg-gray-50 border border-gray-200 rounded-xl px-4 py-3 text-sm text-gray-800" placeholder="123 Street Ave" value="${checkoutData.shipping.address||''}"></div><div class="grid grid-cols-2 gap-4"><div><label class="text-[10px] uppercase tracking-[.2em] text-gray-400 block mb-1.5">City</label><input type="text" id="s-city" class="w-full bg-gray-50 border border-gray-200 rounded-xl px-4 py-3 text-sm text-gray-800" placeholder="New York" value="${checkoutData.shipping.city||''}"></div><div><label class="text-[10px] uppercase tracking-[.2em] text-gray-400 block mb-1.5">ZIP Code</label><input type="text" id="s-zip" class="w-full bg-gray-50 border border-gray-200 rounded-xl px-4 py-3 text-sm text-gray-800" placeholder="10001" value="${checkoutData.shipping.zip||''}"></div></div></div><button onclick="submitShipping()" class="btn-primary mt-8 w-full py-4 bg-gray-900 text-white font-bold text-sm uppercase tracking-[.2em] rounded-full">Continue to Payment</button></div>`}
else if(checkoutStep===2){formHTML=`<div class="bg-white rounded-2xl p-8 max-w-lg mx-auto scale-in shadow-lg border border-gray-100"><h2 class="font-serif text-xl font-bold text-gray-900 mb-6">Payment Details</h2><div class="space-y-4" id="payment-form"><div><label class="text-[10px] uppercase tracking-[.2em] text-gray-400 block mb-1.5">Cardholder Name</label><input type="text" id="p-name" class="w-full bg-gray-50 border border-gray-200 rounded-xl px-4 py-3 text-sm text-gray-800" placeholder="JOHN DOE" value="${checkoutData.payment.name||''}"></div><div><label class="text-[10px] uppercase tracking-[.2em] text-gray-400 block mb-1.5">Card Number</label><input type="text" id="p-card" maxlength="19" class="w-full bg-gray-50 border border-gray-200 rounded-xl px-4 py-3 text-sm text-gray-800 tracking-widest" placeholder="4242 4242 4242 4242" value="${checkoutData.payment.card||''}"></div><div class="grid grid-cols-2 gap-4"><div><label class="text-[10px] uppercase tracking-[.2em] text-gray-400 block mb-1.5">Expiry</label><input type="text" id="p-expiry" maxlength="5" class="w-full bg-gray-50 border border-gray-200 rounded-xl px-4 py-3 text-sm text-gray-800 tracking-widest" placeholder="MM/YY" value="${checkoutData.payment.expiry||''}"></div><div><label class="text-[10px] uppercase tracking-[.2em] text-gray-400 block mb-1.5">CVV</label><input type="text" id="p-cvv" maxlength="4" class="w-full bg-gray-50 border border-gray-200 rounded-xl px-4 py-3 text-sm text-gray-800 tracking-widest" placeholder="···" value="${checkoutData.payment.cvv||''}"></div></div></div><div class="flex gap-3 mt-8"><button onclick="checkoutStep=1;renderCheckout(document.getElementById('app'))" class="py-4 px-6 bg-white border border-gray-200 rounded-full text-sm font-medium tracking-wider uppercase text-gray-600 hover:border-gray-400 transition-colors">Back</button><button onclick="submitPayment()" class="btn-primary flex-1 py-4 bg-gray-900 text-white font-bold text-sm uppercase tracking-[.2em] rounded-full">Review Order</button></div></div>`}
else if(checkoutStep===3){const total=Cart.total();formHTML=`<div class="bg-white rounded-2xl p-8 max-w-lg mx-auto scale-in shadow-lg border border-gray-100"><h2 class="font-serif text-xl font-bold text-gray-900 mb-6">Order Review</h2><div class="space-y-3 mb-6">${cart.map(item=>{const p=PRODUCTS.find(x=>x.id===item.id);return p?`<div class="flex justify-between items-center py-2 border-b border-gray-100"><div><span class="text-sm text-gray-800">${p.name}</span><span class="text-gray-400 text-xs ml-2">×${item.qty}</span></div><span class="text-sm font-semibold text-gray-900">$${(p.price*item.qty).toFixed(2)}</span></div>`:''}).join('')}</div><div class="space-y-2 pt-4"><div class="flex justify-between text-sm"><span class="text-gray-400">Subtotal</span><span class="text-gray-800">$${total.toFixed(2)}</span></div><div class="flex justify-between text-sm"><span class="text-gray-400">Shipping</span><span class="text-accent text-xs">FREE</span></div><div class="flex justify-between text-lg pt-3 border-t border-gray-100"><span class="font-bold text-gray-900">Total</span><span class="font-black text-gray-900">$${total.toFixed(2)}</span></div></div><div class="mt-6 p-4 rounded-xl bg-gray-50 border border-gray-100 text-xs text-gray-400 space-y-1"><p><span class="text-gray-500">Ship to:</span> ${checkoutData.shipping.fname} ${checkoutData.shipping.lname}, ${checkoutData.shipping.address}, ${checkoutData.shipping.city} ${checkoutData.shipping.zip}</p><p><span class="text-gray-500">Card:</span> •••• •••• •••• ${(checkoutData.payment.card||'').slice(-4)}</p></div><div class="flex gap-3 mt-8"><button onclick="checkoutStep=2;renderCheckout(document.getElementById('app'))" class="py-4 px-6 bg-white border border-gray-200 rounded-full text-sm font-medium tracking-wider uppercase text-gray-600 hover:border-gray-400 transition-colors">Back</button><button onclick="placeOrder()" class="btn-primary flex-1 py-4 bg-gray-900 text-white font-bold text-sm uppercase tracking-[.2em] rounded-full">Place Order</button></div></div>`}
else if(checkoutStep===4){formHTML=`<div class="flex flex-col items-center justify-center py-20 scale-in"><div class="w-16 h-16 border-4 border-accent/20 border-t-accent rounded-full spinner"></div><p class="mt-8 text-gray-400 text-sm tracking-[.15em] uppercase">Processing your order…</p></div>`}
else if(checkoutStep===5){const orderId='PB-'+Math.random().toString(36).substring(2,8).toUpperCase();formHTML=`<div class="text-center py-12 scale-in"><div class="w-20 h-20 mx-auto rounded-full bg-accent-pale flex items-center justify-center mb-6" style="animation:checkPop .6s cubic-bezier(.16,1,.3,1) forwards"><svg class="w-10 h-10 text-accent" fill="none" stroke="currentColor" stroke-width="2.5" viewBox="0 0 24 24"><polyline points="20 6 9 17 4 12"/></svg></div><h2 class="font-serif text-3xl font-bold text-gray-900">Order Confirmed</h2><p class="text-gray-400 mt-3">Thank you for choosing Prismon Black.</p><div class="inline-block mt-6 px-6 py-3 rounded-xl bg-gray-50 border border-gray-100"><span class="text-[10px] uppercase tracking-[.2em] text-gray-400">Order ID</span><p class="text-accent font-bold text-lg tracking-[.1em] mt-1">${orderId}</p></div><div class="mt-10"><button onclick="checkoutStep=1;checkoutData={shipping:{},payment:{}};navigate('catalog')" class="btn-primary px-10 py-4 bg-gray-900 text-white font-bold text-sm uppercase tracking-[.2em] rounded-full">Continue Shopping</button></div></div>`}
app.innerHTML=`<section class="max-w-3xl mx-auto px-4 sm:px-6 py-12 sm:py-16 min-h-[80vh]"><div class="text-center mb-8"><p class="text-accent text-xs font-semibold tracking-[.3em] uppercase mb-3">Secure Checkout</p><h1 class="font-serif text-3xl sm:text-4xl font-bold text-gray-900">Checkout</h1></div>${checkoutStep<=3?progressHTML:''}${formHTML}</section>`}
function submitShipping(){const f=id=>(document.getElementById(id)||{}).value||'';const d={fname:f('s-fname'),lname:f('s-lname'),email:f('s-email'),address:f('s-address'),city:f('s-city'),zip:f('s-zip')};if(!d.fname||!d.lname||!d.email||!d.address||!d.city||!d.zip){Toast.show('Please fill in all fields','error');return}checkoutData.shipping=d;checkoutStep=2;renderCheckout(document.getElementById('app'))}
function submitPayment(){const f=id=>(document.getElementById(id)||{}).value||'';const d={name:f('p-name'),card:f('p-card'),expiry:f('p-expiry'),cvv:f('p-cvv')};if(!d.name||!d.card||!d.expiry||!d.cvv){Toast.show('Please fill in all fields','error');return}checkoutData.payment=d;checkoutStep=3;renderCheckout(document.getElementById('app'))}
function placeOrder(){checkoutStep=4;renderCheckout(document.getElementById('app'));setTimeout(()=>{Cart.clear();checkoutStep=5;renderCheckout(document.getElementById('app'));Toast.show('Order placed successfully!','success')},2000)}
const Chatbot={
open:false,
toggle(){this.open=!this.open;const w=document.getElementById('chat-window');if(!w)return;if(this.open){w.classList.remove('hidden');w.classList.add('flex');if(!document.getElementById('chat-messages').children.length){this.addMsg('Welcome to Prismon Black! 🌿 How can I help you today? Ask about shipping, returns, ingredients, or anything else.',true)}}else{w.classList.add('hidden');w.classList.remove('flex')}},
send(){const input=document.getElementById('chat-input');if(!input)return;const text=input.value.trim();if(!text)return;input.value='';this.addMsg(text,false);this.showTyping();setTimeout(()=>{this.hideTyping();this.addMsg(this.getResponse(text),true)},1200+Math.random()*800)},
getResponse(text){const t=text.toLowerCase();if(t.includes('shipping')||t.includes('delivery'))return'Shipping is free on all orders! 📦 Standard delivery takes 3-5 business days. Express shipping (1-2 days) is available for $12.';if(t.includes('return')||t.includes('refund'))return'We offer a 30-day hassle-free return policy on all unopened products. Simply email us at hello@prismonblack.com to initiate. 💜';if(t.includes('ingredient')||t.includes('natural')||t.includes('vegan'))return'All our products are 100% natural, cruelty-free, and vegan. 🌱 Full ingredient lists are on each product page.';if(t.includes('contact')||t.includes('email')||t.includes('help'))return'Our care team is available Mon-Fri, 9am-6pm EST. 📧 Email: hello@prismonblack.com';if(t.includes('payment')||t.includes('pay')||t.includes('card'))return'We accept all major credit cards, Apple Pay, and Google Pay. All transactions are 256-bit SSL encrypted. 🔒';if(t.includes('track')||t.includes('order')||t.includes('status'))return'Track your order via the confirmation email sent after purchase. Updates at every stage! 🚚';if(t.includes('hi')||t.includes('hello')||t.includes('hey'))return'Hello! 👋 Welcome to Prismon Black. How can I help you today?';return'Thank you for your message! 💜 Try asking about shipping, returns, ingredients, or payments. You can also email hello@prismonblack.com.'},
addMsg(text,isBot){const c=document.getElementById('chat-messages');if(!c)return;const m=document.createElement('div');m.className=`flex ${isBot?'justify-start':'justify-end'}`;m.innerHTML=`<div class="max-w-[80%] px-4 py-2.5 rounded-2xl text-sm leading-relaxed ${isBot?'bg-white shadow-sm border border-gray-100 text-gray-700 rounded-tl-sm':'bg-accent text-white rounded-tr-sm'}">${text}</div>`;c.appendChild(m);c.scrollTop=c.scrollHeight},
showTyping(){const c=document.getElementById('chat-messages');if(!c)return;const t=document.createElement('div');t.id='typing-ind';t.className='flex justify-start';t.innerHTML='<div class="px-4 py-3 rounded-2xl rounded-tl-sm bg-white shadow-sm border border-gray-100"><span class="typing-dot"></span><span class="typing-dot"></span><span class="typing-dot"></span></div>';c.appendChild(t);c.scrollTop=c.scrollHeight},
hideTyping(){const t=document.getElementById('typing-ind');if(t)t.remove()}
};
/* Init */
const _cartToggle=document.getElementById('cart-toggle');if(_cartToggle)_cartToggle.addEventListener('click',toggleCart);
const _cartOverlay=document.getElementById('cart-overlay');if(_cartOverlay)_cartOverlay.addEventListener('click',toggleCart);
const _modalOverlay=document.getElementById('modal-overlay');if(_modalOverlay)_modalOverlay.addEventListener('click',closeModal);
window.addEventListener('hashchange',handleRoute);
document.addEventListener('keydown',e=>{if(e.key==='Escape'){const modal=document.getElementById('product-modal');if(modal&&!modal.classList.contains('hidden'))closeModal();else if(document.getElementById('cart-drawer')&&!document.getElementById('cart-drawer').classList.contains('translate-x-full'))toggleCart();else if(Chatbot.open)Chatbot.toggle()}});
Cart.badge();handleRoute();
